### ISSUE TITLE
Please make a comfyui version!

### ISSUE THREAD

**Issue by hahajaja** [Faildes/Chattiori-Model-Merger#2]
comfyui can test merge models elegantly!
[ComfyUI_examples](https://github.com/comfyanonymous/ComfyUI_examples/tree/master/model_merging)

**Comment by Faildes** [comment]
I can see there are some benefits, but this would use extra VRAMs that doesn't need to be used.
Initially, the purpose of this merger is to get the merged model with the least amount of VRAMs.
If you want to test it, you can use [super merger](https://github.com/hako-mikan/sd-webui-supermerger) instead.
But I'll try my best to make the version for comfyui.
Thanks for the suggestion.

**Comment by hahajaja** [comment]
Thanks
